### PR TITLE
Update egui to 0.31

### PR DESCRIPTION
**Pull request by hydra**
Things seems to work, but I've never used egui or this crate until today, but I needed a version that works with egui 0.31 so here we are...

* compilation errors 'fixed' - mostly due to changes for the missing stroke kind on rectangles, I used 'StrokeKind::Inside' everywhere.
* all 'deprecated' warnings removed.
* tests pass
* examples run
* changes formatted using `cargo fmt`.

Most of the changes are relating to CornerRadius changes.

### CODE REVIEW

**Comment by Adanos020** [comment]
Hi, thanks for contributing. There are a few things missing, I'm going to take care of them.
